### ISSUE TITLE
lightning cable interface?

### ISSUE THREAD

**Issue by Mic238** [mkalten/TuioPad#1]
Connect Mac and iOS device would form a network connection over the cable, but this can't be correctly identified by the app. Turning off both wifi and mobile data would prompt no active connection regardless to the cable.

**Comment by mkalten** [comment]
Hi @Mic238 I just tested the configuration and it works fine for me. In order to make it work through a USB/Lightning connection, you will have to enable the Hotspot feature on the iPhone and turn off Wifi on your computer.
